version: "3"
services:
  nginx:
    container_name: nginx-container
    build:
      context: ./nginx
      dockerfile: nginx_Dockerfile
    ports:
      - 80:80
    depends_on:
      - docker-springboot
  docker-springboot:
    container_name: springboot-container
    build: .
    expose:
      - 8080